# https://www.tensorflow.org/tensorboard/

tensorboard:
  _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  save_dir: "/pub2/experiments/ocr/logs"
  name: null
  log_graph: False
  default_hp_metric: True
  prefix: ""
  version: "continue_train"
